"""
github_poster.py — Posts agent review results as GitHub PR review comments.

GitHub PR Review API overview:
  - One "review" object per PR submission = one summary + N inline comments
  - Inline comments attach to specific files + lines in the diff
  - The review event: REQUEST_CHANGES | APPROVE | COMMENT
  - We use the REST API directly (not PyGithub's create_review) because we need
    the `line` parameter which PyGithub doesn't fully expose yet.

Line number handling:
  - GitHub inline comments require the line to be part of the PR diff.
  - If a line isn't in the diff, GitHub rejects the comment (422 error).
  - We handle this gracefully: failed inline comments are included in the
    review body instead, so no information is lost.
"""

import logging
import os
import re
import sys
from dataclasses import dataclass, field
from typing import Optional

import requests
from github import Github, GithubException

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

logger = logging.getLogger("ai_reviewer.github_poster")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_API   = "https://api.github.com"

# Severity → GitHub suggestion prefix
SEVERITY_EMOJI = {
    "CRITICAL": "🔴",
    "HIGH":     "🟠",
    "MEDIUM":   "🟡",
    "LOW":      "🟢",
}

VERDICT_EMOJI = {
    "REQUEST_CHANGES": "❌",
    "APPROVE":         "✅",
    "COMMENT":         "💬",
}


# ─── Output Schema ────────────────────────────────────────────────────────────

@dataclass
class PostResult:
    success: bool
    review_url: str = ""
    review_id: int = 0
    inline_posted: int = 0       # comments successfully posted inline
    inline_fallback: int = 0     # comments that fell back to review body
    error: Optional[str] = None


# ─── URL Parser ───────────────────────────────────────────────────────────────

def _parse_pr_url(pr_url: str) -> tuple[str, str, int]:
    """
    Parse a GitHub PR URL into (owner, repo, pr_number).
    Handles both https://github.com/owner/repo/pull/123 and
    https://github.com/owner/repo/pull/123/files.
    """
    pattern = r"github\.com/([^/]+)/([^/]+)/pull/(\d+)"
    m = re.search(pattern, pr_url)
    if not m:
        raise ValueError(f"Cannot parse GitHub PR URL: {pr_url}")
    return m.group(1), m.group(2), int(m.group(3))


# ─── Review Body Formatter ────────────────────────────────────────────────────

def _build_review_body(agent_review_dict: dict, fallback_comments: list[dict]) -> str:
    """
    Build the markdown body for the GitHub PR review.
    Includes summary, risk level, and any inline comments that couldn't be
    posted inline (e.g. lines not in the diff).
    """
    verdict = agent_review_dict.get("overall_verdict", "COMMENT")
    risk    = agent_review_dict.get("risk_level", "LOW")
    summary = agent_review_dict.get("summary", "")
    tools   = agent_review_dict.get("tools_used", [])
    conf    = agent_review_dict.get("confidence", 0.0)
    meta    = agent_review_dict.get("agent_meta", {})
    pr_type = meta.get("pr_type", "")

    v_emoji = VERDICT_EMOJI.get(verdict, "💬")
    r_emoji = {"HIGH": "🔴", "MEDIUM": "🟡", "LOW": "🟢"}.get(risk, "🟢")

    lines = [
        f"## {v_emoji} AI Code Review — {verdict.replace('_', ' ').title()}",
        "",
        f"**Risk Level:** {r_emoji} {risk} &nbsp;|&nbsp; "
        f"**PR Type:** {pr_type} &nbsp;|&nbsp; "
        f"**Confidence:** {conf:.0%}",
        "",
        f"### Summary",
        summary,
        "",
    ]

    if tools:
        lines += [f"**Tools used:** {', '.join(f'`{t}`' for t in tools)}", ""]

    # Add fallback comments to body if they couldn't be posted inline
    if fallback_comments:
        lines += ["### ⚠️ Additional Findings (could not attach inline)", ""]
        for c in fallback_comments:
            sev = c.get("severity", "LOW")
            emoji = SEVERITY_EMOJI.get(sev, "🟢")
            lines += [
                f"**{emoji} {sev} — `{c.get('file', '')}:{c.get('line', '?')}`** "
                f"({c.get('category', '')})",
                c.get("comment", ""),
            ]
            if c.get("suggestion"):
                lines += ["", f"**Suggested fix:**", f"```", c["suggestion"], "```"]
            lines.append("")

    lines += [
        "---",
        "*Generated by [AI Code Reviewer](https://github.com/) — "
        "Powered by Gemini 2.5 Flash + CodeBERT*",
    ]
    return "\n".join(lines)


def _build_inline_body(comment: dict) -> str:
    """Format a single inline comment body for GitHub."""
    sev   = comment.get("severity", "LOW")
    cat   = comment.get("category", "STYLE")
    emoji = SEVERITY_EMOJI.get(sev, "🟢")
    body  = f"{emoji} **{sev} ({cat}):** {comment.get('comment', '')}"
    if comment.get("suggestion"):
        body += f"\n\n**Suggested fix:**\n```\n{comment['suggestion']}\n```"
    return body


# ─── GitHub API Calls ─────────────────────────────────────────────────────────

def _get_head_sha(owner: str, repo: str, pr_number: int, token: str) -> str:
    """Get the head commit SHA of the PR (required for creating a review)."""
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}"
    resp = requests.get(url, headers={"Authorization": f"token {token}"}, timeout=10)
    resp.raise_for_status()
    return resp.json()["head"]["sha"]


def _post_review(
    owner: str,
    repo: str,
    pr_number: int,
    commit_sha: str,
    body: str,
    event: str,
    comments: list[dict],
    token: str,
) -> dict:
    """
    POST /repos/{owner}/{repo}/pulls/{pr_number}/reviews
    Returns the review JSON response.
    """
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/reviews"
    payload = {
        "commit_id": commit_sha,
        "body":      body,
        "event":     event,   # REQUEST_CHANGES | APPROVE | COMMENT
        "comments":  comments,
    }
    resp = requests.post(
        url,
        json=payload,
        headers={
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github+json",
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()


def _get_diff_lines(
    owner: str, repo: str, pr_number: int, token: str
) -> dict[str, list[int]]:
    """
    Return {filename: sorted list of changed line numbers} for the PR diff.
    Includes both added lines (+) and context lines (space prefix) so that
    comments can be snapped to the nearest reviewable position.
    Only truly deleted lines (-) are excluded.
    """
    url = f"{GITHUB_API}/repos/{owner}/{repo}/pulls/{pr_number}/files"
    resp = requests.get(
        url,
        headers={"Authorization": f"token {token}"},
        params={"per_page": 100},
        timeout=15,
    )
    resp.raise_for_status()

    diff_lines: dict[str, list[int]] = {}
    for file_info in resp.json():
        filename = file_info.get("filename", "")
        patch    = file_info.get("patch", "")
        if not patch:
            continue

        lines_in_diff: list[int] = []
        current_line = 0
        for diff_line in patch.split("\n"):
            if diff_line.startswith("@@"):
                m = re.search(r"\+(\d+)", diff_line)
                if m:
                    current_line = int(m.group(1)) - 1
            elif diff_line.startswith("-"):
                pass  # deleted — no new line number
            else:
                current_line += 1
                lines_in_diff.append(current_line)

        if lines_in_diff:
            diff_lines[filename] = sorted(set(lines_in_diff))

    return diff_lines


def _snap_to_diff_line(
    file_path: str,
    line_num: int,
    diff_lines: dict[str, list[int]],
) -> int | None:
    """
    Snap a line number to the nearest changed line in the same file.
    Returns the snapped line number, or None if the file isn't in the diff at all.
    """
    file_lines = diff_lines.get(file_path)
    if not file_lines:
        return None  # file not in diff → cannot post inline
    # Find closest line using min distance
    return min(file_lines, key=lambda l: abs(l - line_num))


# ─── Main Entry Point ─────────────────────────────────────────────────────────

def post_review_to_github(
    pr_url: str,
    agent_review_dict: dict,
    github_token: str = None,
) -> PostResult:
    """
    Post the agent review as a GitHub PR review with inline comments.

    Args:
        pr_url:             GitHub PR URL
        agent_review_dict:  Output of agent_review_to_dict()
        github_token:       GitHub personal access token (defaults to GITHUB_TOKEN env var)

    Returns:
        PostResult with success status and stats
    """
    token = github_token or GITHUB_TOKEN
    if not token:
        return PostResult(
            success=False,
            error="GITHUB_TOKEN not set. Add it to your .env file.",
        )

    try:
        owner, repo, pr_number = _parse_pr_url(pr_url)
    except ValueError as e:
        return PostResult(success=False, error=str(e))

    # Map agent verdict to GitHub event
    verdict = agent_review_dict.get("overall_verdict", "COMMENT")
    github_event = {
        "REQUEST_CHANGES": "REQUEST_CHANGES",
        "APPROVE":         "APPROVE",
        "COMMENT":         "COMMENT",
    }.get(verdict, "COMMENT")

    inline_comments_raw = agent_review_dict.get("inline_comments", [])

    try:
        # Get head commit SHA
        commit_sha = _get_head_sha(owner, repo, pr_number, token)
        logger.info(f"Head SHA: {commit_sha[:8]} | PR #{pr_number}")

        # Get valid diff lines to know which inline comments GitHub will accept
        try:
            diff_lines = _get_diff_lines(owner, repo, pr_number, token)
            total_diff = sum(len(v) for v in diff_lines.values())
            logger.info(f"Diff lines available: {total_diff} across {len(diff_lines)} files")
        except Exception as e:
            logger.warning(f"Could not fetch diff lines: {e}. Will try all inline comments.")
            diff_lines = None

        # Map each inline comment to the best available diff line.
        # If the exact line is in the diff → use it.
        # If not → snap to nearest changed line in the same file.
        # If the file isn't in the diff at all → fall back to review body.
        inline_to_post = []
        fallback_comments = []

        for c in inline_comments_raw:
            file_path = c.get("file", "")
            line_num  = c.get("line", 1)

            if diff_lines is None:
                # Couldn't fetch diff — try inline as-is (GitHub may reject some)
                snapped = line_num
            else:
                snapped = _snap_to_diff_line(file_path, line_num, diff_lines)

            if snapped is not None:
                if snapped != line_num:
                    logger.info(
                        f"Snapped {file_path}:{line_num} → :{snapped} "
                        f"(nearest diff line)"
                    )
                inline_to_post.append({
                    "path": file_path,
                    "line": snapped,
                    "side": "RIGHT",
                    "body": _build_inline_body(c),
                })
            else:
                fallback_comments.append(c)
                logger.info(
                    f"{file_path} not in diff — comment will appear in review body"
                )

        # Build review body
        review_body = _build_review_body(agent_review_dict, fallback_comments)

        # Post the review
        logger.info(
            f"Posting review: event={github_event} "
            f"inline={len(inline_to_post)} fallback={len(fallback_comments)}"
        )
        try:
            review_response = _post_review(
                owner=owner, repo=repo, pr_number=pr_number,
                commit_sha=commit_sha, body=review_body,
                event=github_event, comments=inline_to_post, token=token,
            )
        except requests.exceptions.HTTPError as e:
            # GitHub blocks REQUEST_CHANGES on your own PR — retry as COMMENT
            if (e.response is not None and e.response.status_code == 422
                    and "own pull request" in e.response.text
                    and github_event == "REQUEST_CHANGES"):
                logger.warning(
                    "Cannot REQUEST_CHANGES on own PR — retrying as COMMENT"
                )
                review_response = _post_review(
                    owner=owner, repo=repo, pr_number=pr_number,
                    commit_sha=commit_sha, body=review_body,
                    event="COMMENT", comments=inline_to_post, token=token,
                )
            else:
                raise

        review_url = review_response.get("html_url", "")
        review_id  = review_response.get("id", 0)
        logger.info(f"Review posted: {review_url}")

        return PostResult(
            success=True,
            review_url=review_url,
            review_id=review_id,
            inline_posted=len(inline_to_post),
            inline_fallback=len(fallback_comments),
        )

    except requests.exceptions.HTTPError as e:
        status = e.response.status_code if e.response is not None else "?"
        body   = e.response.text[:300] if e.response is not None else ""
        msg = f"GitHub API error {status}: {body}"
        logger.error(msg)
        return PostResult(success=False, error=msg)

    except Exception as e:
        logger.error(f"Failed to post review: {e}", exc_info=True)
        return PostResult(success=False, error=str(e))
